package com.chinamobo.ue.exam.dao;

import java.util.List;
import java.util.Map;

import com.chinamobo.ue.exam.entity.TomExamEmpAllocation;

public interface TomExamEmpAllocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_EXAM_EMP_ALLOCATION
     *
     * @mbggenerated
     */
    int insert(TomExamEmpAllocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_EXAM_EMP_ALLOCATION
     *
     * @mbggenerated
     */
    int insertSelective(TomExamEmpAllocation record);
    /**
     * 
    	 * 功能描述：[批量插入考试人员关联关系]
    	 * 创建者：WChao 创建时间: 2017年6月29日 下午1:57:22
    	 * @param examEmps
    	 * @return
    	 *
     */
    int insertSelectiveBatch(List<TomExamEmpAllocation> examEmps);
    
    /**
     * 
     * 功能描述：[查询关联试卷或者关联员工]
     *
     * 创建者：JCX
     * 创建时间: 2016年4月1日 上午10:11:05
     * @param example
     * @return
     */
    List<TomExamEmpAllocation> selectListByExample(TomExamEmpAllocation example);

    /**
     * 
     * 功能描述：[删除关联]
     *
     * 创建者：JCX
     * 创建时间: 2016年4月1日 上午10:14:47
     * @param example
     */
	void deleteByExample(TomExamEmpAllocation example); 
	
	//根据人员Code与考试ID查询
	TomExamEmpAllocation selectByCodeExamId(Map<Object,Object> map);
}