package com.chinamobo.ue.exam.entity;

import java.util.Date;

public class TomTopicOption {
	
	private String optionKeyAndName;//abc 和选项
	
	private String optionFileUrl;//选项附件
	
	private String isOpen;//选项是否开放
	
	
    public String getIsOpen() {
		return isOpen;
	}

	public void setIsOpen(String isOpen) {
		this.isOpen = isOpen;
	}

	public String getOptionKeyAndName() {
		return optionKeyAndName;
	}

	public void setOptionKeyAndName(String optionKeyAndName) {
		this.optionKeyAndName = optionKeyAndName;
	}

	public String getOptionFileUrl() {
		return optionFileUrl;
	}

	public void setOptionFileUrl(String optionFileUrl) {
		this.optionFileUrl = optionFileUrl;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_TOPIC_OPTION.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_TOPIC_OPTION.OPTION_NAME
     *
     * @mbggenerated
     */
    private String optionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_TOPIC_OPTION.TOPIC_ID
     *
     * @mbggenerated
     */
    private Integer topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_TOPIC_OPTION.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_TOPIC_OPTION.RIGHT
     *
     * @mbggenerated
     */
    private String right;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_TOPIC_OPTION.ID
     *
     * @return the value of TOM_TOPIC_OPTION.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_TOPIC_OPTION.ID
     *
     * @param id the value for TOM_TOPIC_OPTION.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_TOPIC_OPTION.OPTION_NAME
     *
     * @return the value of TOM_TOPIC_OPTION.OPTION_NAME
     *
     * @mbggenerated
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_TOPIC_OPTION.OPTION_NAME
     *
     * @param optionName the value for TOM_TOPIC_OPTION.OPTION_NAME
     *
     * @mbggenerated
     */
    public void setOptionName(String optionName) {
        this.optionName = optionName == null ? null : optionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_TOPIC_OPTION.TOPIC_ID
     *
     * @return the value of TOM_TOPIC_OPTION.TOPIC_ID
     *
     * @mbggenerated
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_TOPIC_OPTION.TOPIC_ID
     *
     * @param topicId the value for TOM_TOPIC_OPTION.TOPIC_ID
     *
     * @mbggenerated
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_TOPIC_OPTION.CREATE_TIME
     *
     * @return the value of TOM_TOPIC_OPTION.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_TOPIC_OPTION.CREATE_TIME
     *
     * @param createTime the value for TOM_TOPIC_OPTION.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_TOPIC_OPTION.RIGHT
     *
     * @return the value of TOM_TOPIC_OPTION.RIGHT
     *
     * @mbggenerated
     */
    public String getRight() {
        return right;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_TOPIC_OPTION.RIGHT
     *
     * @param right the value for TOM_TOPIC_OPTION.RIGHT
     *
     * @mbggenerated
     */
    public void setRight(String right) {
        this.right = right == null ? null : right.trim();
    }

}