package com.chinamobo.ue.exam.entity;

import java.util.Date;
import java.util.List;

public class TomTopic {
	
	private String questionImgUrl;//题目是图片
	
	private String questionFileUrl;//题目是文件
	
	private String questionAnswer;//正确答案
	
	private String  questionName;//題目名字
	
	private String isSkip;//题目是否跳过
	
	public String getIsSkip() {
		return isSkip;
	}

	public void setIsSkip(String isSkip) {
		this.isSkip = isSkip;
	}

	private List<TomTopicOption>questionOptions ;//临时字段-选项集合
	private List<String> questionKeys;
	
	
	public List<TomTopicOption> getQuestionOptions() {
		return questionOptions;
	}

	public void setQuestionOptions(List<TomTopicOption> questionOptions) {
		this.questionOptions = questionOptions;
	}

	public String getQuestionAnswer() {
		return questionAnswer;
	}

	public void setQuestionAnswer(String questionAnswer) {
		this.questionAnswer = questionAnswer;
	}

	public String getQuestionImgUrl() {
		return questionImgUrl;
	}

	public void setQuestionImgUrl(String questionImgUrl) {
		this.questionImgUrl = questionImgUrl;
	}

	public String getQuestionFileUrl() {
		return questionFileUrl;
	}

	public void setQuestionFileUrl(String questionFileUrl) {
		this.questionFileUrl = questionFileUrl;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_TOPIC.TOPIC_ID
     *
     * @mbggenerated
     */
    private Integer topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_TOPIC.TOPIC_NAME
     *
     * @mbggenerated
     */
    private String topicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_TOPIC.QUESTION_BANK_ID
     *
     * @mbggenerated
     */
    private Integer questionBankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_TOPIC.QUESTION_TYPE
     *
     * @mbggenerated
     */
    private String questionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_TOPIC.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_TOPIC.TOPIC_ID
     *
     * @return the value of TOM_TOPIC.TOPIC_ID
     *
     * @mbggenerated
     */
    private List<TomTopicOption> topicOptions;
    
    private String answer="";
    
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_TOPIC.TOPIC_ID
     *
     * @param topicId the value for TOM_TOPIC.TOPIC_ID
     *
     * @mbggenerated
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_TOPIC.TOPIC_NAME
     *
     * @return the value of TOM_TOPIC.TOPIC_NAME
     *
     * @mbggenerated
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_TOPIC.TOPIC_NAME
     *
     * @param topicName the value for TOM_TOPIC.TOPIC_NAME
     *
     * @mbggenerated
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName == null ? null : topicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_TOPIC.QUESTION_BANK_ID
     *
     * @return the value of TOM_TOPIC.QUESTION_BANK_ID
     *
     * @mbggenerated
     */
    public Integer getQuestionBankId() {
        return questionBankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_TOPIC.QUESTION_BANK_ID
     *
     * @param questionBankId the value for TOM_TOPIC.QUESTION_BANK_ID
     *
     * @mbggenerated
     */
    public void setQuestionBankId(Integer questionBankId) {
        this.questionBankId = questionBankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_TOPIC.QUESTION_TYPE
     *
     * @return the value of TOM_TOPIC.QUESTION_TYPE
     *
     * @mbggenerated
     */
    public String getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_TOPIC.QUESTION_TYPE
     *
     * @param questionType the value for TOM_TOPIC.QUESTION_TYPE
     *
     * @mbggenerated
     */
    public void setQuestionType(String questionType) {
        this.questionType = questionType == null ? null : questionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_TOPIC.CREATE_TIME
     *
     * @return the value of TOM_TOPIC.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_TOPIC.CREATE_TIME
     *
     * @param createTime the value for TOM_TOPIC.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public List<TomTopicOption> getTopicOptions() {
		return topicOptions;
	}

	public void setTopicOptions(List<TomTopicOption> topicOptions) {
		this.topicOptions = topicOptions;
	}

	public String getAnswer() {
		return answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public List<String> getQuestionKeys() {
		return questionKeys;
	}

	public void setQuestionKeys(List<String> questionKeys) {
		this.questionKeys = questionKeys;
	}

	public String getQuestionName() {
		return questionName;
	}

	public void setQuestionName(String questionName) {
		this.questionName = questionName;
	}


}