package com.chinamobo.ue.activity.dao;

import java.util.List;
import java.util.Map;

import com.chinamobo.ue.activity.entity.TomActivityEmpsRelation;
import com.chinamobo.ue.activity.entity.TomActivityEmpsRelationKey;

public interface TomActivityEmpsRelationMapper {//extends BaseDao<TomActivityEmpsRelationKey>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_EMPS_RELATION
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TomActivityEmpsRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_EMPS_RELATION
     *
     * @mbggenerated
     */
    int insert(TomActivityEmpsRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_EMPS_RELATION
     *
     * @mbggenerated
     */
    int insertSelective(TomActivityEmpsRelation record);
    /**
     * 
    	 * 功能描述：[批量添加活动配置人员关系表]
    	 * 创建者：WChao 创建时间: 2017年6月29日 下午2:26:48
    	 * @param activityEmpsRelations
    	 * @return
    	 *
     */
    int insertSelectiveBatch(List<TomActivityEmpsRelation> activityEmpsRelations);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_EMPS_RELATION
     *
     * @mbggenerated
     */
    TomActivityEmpsRelation selectByPrimaryKey(TomActivityEmpsRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_EMPS_RELATION
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomActivityEmpsRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_EMPS_RELATION
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomActivityEmpsRelation record);

	List<TomActivityEmpsRelation> selectByActivityId(int activityId);
	
	List<TomActivityEmpsRelation> selectByActivityIds(int activityId);

	List<TomActivityEmpsRelation> selectByActivitycode(String code);
	/**
	 * 
	 * 功能描述：[根据活动ID删除]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年5月25日 下午4:20:53
	 * @param activityId
	 */
	void deleteByActivityId(Integer activityId);

	int countByExample(TomActivityEmpsRelation record);
	
	int countByExamples(TomActivityEmpsRelation record);

	/**
	 * 
	 * 功能描述：[查询活动人员关联]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年5月29日 下午5:14:26
	 * @param empsRelationExample
	 * @return
	 */
	List<TomActivityEmpsRelation> selectListByExample(
			TomActivityEmpsRelation empsRelationExample);
	
	List<TomActivityEmpsRelation> selectListExample(Map<Object,Object> map);
	
	//用于消息查询活动中的人
	List<TomActivityEmpsRelation> selectByActivityId2(int activityId);
	
	List<TomActivityEmpsRelation> selectLabelEmp(Map<Object,Object> map);
	
	List<TomActivityEmpsRelation> selectEmp(Map<Object,Object> map);
}